; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
description = Basic SPI Slave example for Teensy 4.1

[env]
lib_compat_mode = strict
lib_ldf_mode = deep+
build_flags = 
	; -D BOARD_NAME="TEENSY 4.1"
	-D BOARD_TYPE="TEENSY 4.1"
	-O3 ; enables fast optimizations https://stackoverflow.com/questions/49056128/any-possible-code-that-can-flip-a-bit-integer-bool-between-0-and-1-in-single-cpu

[env:teensy41]
platform = teensy@5.0
board = teensy41
framework = arduino
lib_deps =
    SlaveSPIT4=symlink://C:/Users/emore/source/repos/emorell96/SlaveSPIT4/